### ISSUE TITLE
Add to Awesome-D3

### ISSUE THREAD

**Issue by curran** [petulla/d3-hsluv#1]
This library is an exciting development!

@petulla Once you feel it's ready for prime time, I suggest we add it to https://github.com/wbkd/awesome-d3

**Comment by petulla** [comment]
@curran Sounds good, will let you know. Waiting on Mike to discuss next steps.

**Comment by petulla** [comment]
@curran This is ready to be added. I'm writing an introduction blog post.

**Comment by curran** [comment]
@petulla Done! https://github.com/wbkd/awesome-d3/pull/61
